const multipleChoice = [
  { category: 'P1 · PLANIFICACIÓN', typeLabel: 'SELECCIÓN MÚLTIPLE', text: '¿Cuál fue el fallo metodológico principal que permitió descubrir el retraso del prototipo solo 48 horas antes?', answers: ['Dividir el trabajo bajo un modelo donde cada integrante avanzaba de forma autónoma, sin establecer entregas parciales ni reuniones de revisión obligatorias.', 'Malinterpretar el rol del líder de equipo, al no haber designado a un co-líder que auditara semanalmente el cumplimiento de los tiempos de cada área.', 'No haber reasignado la elaboración del prototipo a dos o más personas desde la primera semana, dada la complejidad técnica y la alta carga de la tarea.', 'Omitir en la matriz de riesgos del proyecto la demora en las revisiones del instructor como un factor crítico para el cronograma.'], correct: 0, explanation: 'El fallo no fue de actitud ni de personas, sino de método de trabajo. Al dejar que cada persona avanzara por su cuenta sin fechas intermedias para mostrar avances, el equipo se quedó a ciegas. Las revisiones no se hacen por desconfianza, sino para detectar frenos a tiempo.', wrongExplanations: ['Esta opción es la correcta, por eso no está mal.', 'Crear la figura de un co-líder en un equipo pequeño no garantiza transparencia si la metodología sigue siendo la misma. El problema no es quién supervisa, sino la falta de un calendario formal de revisiones.', 'Ataca la sobrecarga, pero no la causa raíz. Si dos personas trabajaran en el prototipo sin revisiones intermedias, el equipo habría llegado exactamente al mismo punto ciego a 48 horas de la entrega.', 'Aunque identificar el riesgo es una buena práctica, la sola matriz de riesgos no evita el problema si internamente el equipo no monitorea el impacto del retraso a tiempo para ajustar su plan.'] },
  { category: 'P2 · EMPATÍA', typeLabel: 'SELECCIÓN MÚLTIPLE', text: 'Cuando el retraso sale a la luz, Carlos y Daniela sostienen que su responsabilidad concluía al entregar la parte teórica. ¿Por qué este enfoque representa una falla?', answers: ['Porque demuestra falta de seguimiento al trabajo ajeno, ya que debieron estar revisando el avance de Sofía desde el primer día para evitar sorpresas.', 'Porque rompe el principio de apoyo mutuo, ya que al terminar su parte debieron ponerse a disposición de quien estaba colgado con el trabajo.', 'Porque asume que las partes del proyecto son independientes, cuando en realidad la teoría no sirve de nada si el prototipo no se presenta.', 'Porque prioriza el cumplimiento de tareas individuales por encima de la entrega final, ignorando que si el proyecto falla, la responsabilidad es de todos.'], correct: 3, explanation: 'En un equipo no existen victorias ni derrotas individuales. Decir “yo ya cumplí con lo mío” demuestra una mentalidad individualista donde importa más lavarse las manos que lograr el objetivo común.', wrongExplanations: ['Hace pensar que la obligación de los compañeros era “vigilar” o “auditar” a Sofía para que no se atrasara. Su rol no era convertirse en policías ni supervisores de su compañera, sino mantener una comunicación abierta sobre la marcha general del proyecto.', 'Apoyar al compañero es una buena práctica, pero no la falla principal. El error de fondo de Carlos y Daniela fue la postura de desentenderse por completo del resultado final, no el hecho de no haber hecho el trabajo de Sofía.', 'Se enfoca en el valor de la nota o del documento entregado, en lugar de señalar el verdadero problema de fondo, que es la falta de empatía y trabajo colaborativo.', 'Esta opción es la correcta, por eso no está mal.'] },
  { category: 'P3 · CRISIS', typeLabel: 'SELECCIÓN MÚLTIPLE', text: 'A 48 horas de la entrega y con el retraso confirmado, ¿cuál es la decisión estratégica que debe tomar el equipo?', answers: ['Delegar la responsabilidad total al líder del equipo para que concentre la toma de decisiones y redacte la solución durante la noche.', 'Recomponer la carga de trabajo, ajustando el alcance del prototipo a lo esencial y redistribuyendo tareas para apoyar el cierre.', 'Escalar el caso de inmediato al instructor para reportar el incumplimiento individual y solicitar una evaluación diferenciada.', 'Suspender el desarrollo del prototipo para ajustar y pulir la teoría existente, entregando un documento impecable, aunque incompleto.'], correct: 1, explanation: 'Muestra una gestión efectiva de crisis basada en la adaptabilidad. Lo correcto es priorizar las funcionalidades o elementos mínimos viables, redistribuir los esfuerzos y sacar adelante el objetivo común en equipo.', wrongExplanations: ['Promueve la sobrecarga extrema y el agotamiento del líder, impidiendo el apoyo colaborativo y afectando la calidad del entregable.', 'Esta opción es la correcta, por eso no está mal.', 'A 48 horas del cierre, enfocar la energía en buscar culpables ante el instructor demuestra falta de capacidad interna de resolución de problemas.', 'En las evaluaciones de proyecto, dejar un componente obligatorio en blanco invalida la entrega general; es preferible presentar un prototipo funcional básico que omitirlo por completo.'] },
  { category: 'P4 · LIDERAZGO', typeLabel: 'SELECCIÓN MÚLTIPLE', text: 'Mateo asumió que el proyecto avanzaba sin problemas al no haber quejas en el chat de WhatsApp. ¿Por qué esta actitud revela un defecto grave de liderazgo?', answers: ['Porque el rol del líder exige tomar el control absoluto de las áreas técnicas retrasadas tan pronto como los integrantes muestran lentitud.', 'Porque sustituyó el seguimiento activo y la verificación de evidencias reales por una suposición pasiva basada en la ausencia de conflicto.', 'Porque omitió reportar oportunamente al instructor que los integrantes no estaban usando los canales oficiales para enviar sus aportes.', 'Porque debió haber reestructurado la asignación de roles de manera unilateral desde la segunda semana de trabajo.'], correct: 1, explanation: '¡CORRECTA! Confundir el silencio en los chats con avance real es un error; el seguimiento exige revisar entregables e hitos visibles programados.', wrongExplanations: ['El rol del líder no es asumir el trabajo técnico de los demás, sino coordinar, monitorear y desatascar problemas.', 'Esta opción es la correcta, por eso no está mal.', 'El problema de fondo no fue la herramienta de comunicación utilizada, sino la falta de verificación periódica de los avances.', 'Reestructurar roles unilateralmente y sin diagnóstico previo destruye la confianza y la motivación del grupo.'] },
  { category: 'P5 · RESPUESTA', typeLabel: 'SELECCIÓN MÚLTIPLE', text: 'A 48 horas de la entrega y con el retraso confirmado, ¿cuál es la decisión estratégica que debe tomar el equipo para responder a la emergencia?', answers: ['Delegar la responsabilidad total al líder del equipo para que concentre la toma de decisiones y redacte la solución durante la noche.', 'Recomponer la carga de trabajo, ajustando el alcance del prototipo a lo esencial y redistribuyendo tareas para apoyar el cierre.', 'Escalar el caso de inmediato al instructor para reportar el incumplimiento individual y solicitar una evaluación diferenciada.', 'Suspender el desarrollo del prototipo para ajustar y pulir la teoría existente, entregando un documento impecable, aunque incompleto.'], correct: 1, explanation: '¡CORRECTA! Muestra una gestión de crisis basada en la adaptabilidad: se prioriza lo esencial del prototipo, se redistribuyen cargas y se cierra en equipo.', wrongExplanations: ['Promueve la sobrecarga y el agotamiento del líder, impidiendo el trabajo colaborativo y afectando la calidad del entregable.', 'Esta opción es la correcta, por eso no está mal.', 'A 48 horas del cierre, enfocar la energía en buscar culpables ante el instructor demuestra incapacidad interna de resolución de problemas.', 'En las evaluaciones de proyecto, dejar un componente obligatorio en blanco invalida la entrega general; es preferible presentar una versión básica funcional.'] },
  { category: 'P6 · APRENDIZAJE', typeLabel: 'SELECCIÓN MÚLTIPLE', text: 'Terminada la entrega, ¿qué acción estratégica debe implementar el equipo para garantizar que este problema no se repita?', answers: ['Solicitar al centro de formación la reasignación de integrantes para trabajar con compañeros de mayor rendimiento.', 'Realizar una sesión de retroalimentación enfocada en analizar las fallas del proceso y acordar nuevas reglas de funcionamiento.', 'Exigir que en las próximas entregas cada integrante trabaje de manera 100% independiente para evitar depender del ritmo ajeno.', 'Acordar que el líder asuma la supervisión directa de cada archivo antes de que sea compartido con el resto del grupo.'], correct: 1, explanation: '¡CORRECTA! Evaluar el proceso de trabajo en lugar de atacar a las personas permite convertir una crisis en un aprendizaje operativo para el futuro.', wrongExplanations: ['Desintegrar el equipo evade el aprendizaje sobre la resolución de conflictos e integración laboral para el mundo real.', 'Esta opción es la correcta, por eso no está mal.', 'Aumentar el aislamiento destruye la sinergia y profundiza la falta de comunicación que originó la crisis inicial.', 'Obligar a que todo pase por una sola persona genera cuellos de botella, ralentiza el trabajo y elimina la autonomía del equipo.'] }
];

const trueFalse = [
  { category: 'P7 · RESPONSABILIDAD', typeLabel: 'VERDADERO O FALSO', text: 'El principal responsable de la falla en la entrega fue Sofía por no haber solicitado ayuda a tiempo.', answers: ['VERDADERO', 'FALSO'], correct: 1, explanation: 'La falla fue del sistema de trabajo: faltó seguimiento del líder, empatía de los compañeros y revisiones parciales programadas.' },
  { category: 'P8 · CORRESPONSABILIDAD', typeLabel: 'VERDADERO O FALSO', text: 'En el trabajo en equipo, si un integrante termina sus tareas asignadas con anticipación, su nivel de responsabilidad sobre la entrega final disminuye.', answers: ['VERDADERO', 'FALSO'], correct: 1, explanation: 'La responsabilidad sobre el resultado final es del 100% para todo el equipo, sin importar quién terminó primero su parte.' },
  { category: 'P9 · SEGURIDAD PSICOLÓGICA', typeLabel: 'VERDADERO O FALSO', text: 'Crear un ambiente de “seguridad psicológica” significa que los miembros pueden admitir dudas o retrasos sin temor a ser juzgados o atacados.', answers: ['VERDADERO', 'FALSO'], correct: 0, explanation: 'La confianza del entorno permite detectar problemas a tiempo porque las personas no tienen miedo de pedir ayuda antes de la crisis.' },
  { category: 'P10 · CONTINGENCIA', typeLabel: 'VERDADERO O FALSO', text: 'Cuando una tarea depende de la respuesta de un tercero, como la revisión de un instructor, el equipo debe asumir que la fecha límite se extenderá automáticamente.', answers: ['VERDADERO', 'FALSO'], correct: 1, explanation: 'Los imprevistos externos deben gestionarse mediante márgenes de tiempo internos y planes de contingencia creados por el propio grupo.' },
  { category: 'P11 · MÍNIMO VIABLE', typeLabel: 'VERDADERO O FALSO', text: 'La mejor estrategia para afrontar una crisis de tiempo a 48 horas de la entrega es ajustar el alcance a lo esencial y trabajar en conjunto.', answers: ['VERDADERO', 'FALSO'], correct: 0, explanation: 'Ante una emergencia de tiempo, se debe priorizar únicamente lo indispensable para garantizar el cumplimiento del objetivo principal en equipo.' },
  { category: 'P12 · LIDERAZGO', typeLabel: 'VERDADERO O FALSO', text: 'Un líder que asume solo todo el trabajo atrasado durante la noche para salvar la entrega está demostrando un ejemplo ideal de liderazgo en equipo.', answers: ['VERDADERO', 'FALSO'], correct: 1, explanation: 'Centralizar el trabajo sobrecarga al líder, encubre las fallas de organización del grupo y rompe la corresponsabilidad colectiva.' }
];

const STORAGE_KEY = 'mision-entrega-final-partida';
const state = { teams: [{ name: 'Equipo Azul', score: 0, lives: 3, color: 'blue' }, { name: 'Equipo Morado', score: 0, lives: 3, color: 'purple' }], deck: [], question: 0, turn: 0, locked: false, timeLeft: 20, resumeTime: null, timerId: null, phase: 'intro', review: null };
const $ = (id) => document.getElementById(id);
const screens = { intro: $('introScreen'), context: $('contextScreen'), roulette: $('rouletteScreen'), quiz: $('quizScreen'), result: $('resultScreen') };

function shuffle(list) { return [...list].sort(() => Math.random() - 0.5); }
function balancedDeck() {
  const mc = shuffle(multipleChoice); const tf = shuffle(trueFalse); const pairs = [];
  for (let i = 0; i < 6; i++) pairs.push(Math.random() > 0.5 ? [mc[i], tf[i]] : [tf[i], mc[i]]);
  return pairs.flat();
}
function saveGame() { if (!state.deck.length || state.phase === 'intro' || state.phase === 'context' || state.phase === 'roulette') return; const saved = { ...state, timerId: null }; localStorage.setItem(STORAGE_KEY, JSON.stringify(saved)); }
function showScreen(name) { Object.values(screens).forEach(screen => screen.classList.remove('active')); screens[name].classList.add('active'); state.phase = name; $('roundLabel').textContent = name === 'intro' ? 'FASE DE PREPARACIÓN' : name === 'context' ? 'BRIEFING' : name === 'roulette' ? 'SORTEO' : name === 'quiz' ? 'MISIÓN EN CURSO' : 'RESULTADOS'; saveGame(); }
function renderLives(id, lives) { $(id).innerHTML = Array.from({ length: 3 }, (_, i) => `<span class="heart ${i >= lives ? 'lost' : ''}">♥</span>`).join(''); }
function renderScores() { const [blue, purple] = state.teams; $('blueTeamLabel').textContent = blue.name; $('purpleTeamLabel').textContent = purple.name; $('blueScore').innerHTML = `${blue.score} <small>PTS</small>`; $('purpleScore').innerHTML = `${purple.score} <small>PTS</small>`; renderLives('blueLives', blue.lives); renderLives('purpleLives', purple.lives); }
function renderQuestion() {
  const item = state.deck[state.question]; const team = state.teams[state.turn];
  $('questionNumber').textContent = String(state.question + 1).padStart(2, '0'); $('progressFill').style.width = `${((state.question + 1) / state.deck.length) * 100}%`; $('turnBadge').textContent = `TURNO DEL ${team.name.toUpperCase()}`; $('turnBadge').style.color = team.color === 'blue' ? 'var(--blue)' : 'var(--purple)'; $('categoryLabel').textContent = item.category; $('questionType').textContent = item.typeLabel; $('questionText').textContent = item.text;
  $('answers').innerHTML = item.answers.map((answer, i) => `<button class="answer ${item.answers.length === 2 ? 'binary-answer' : ''}" type="button" data-answer="${i}"><b>${item.answers.length === 2 ? i + 1 : String.fromCharCode(65 + i)}</b><span>${answer}</span></button>`).join(''); $('feedback').textContent = ''; $('feedback').className = 'feedback'; $('explanation').hidden = true; $('wrongReview').hidden = true; state.locked = false; document.querySelectorAll('.answer').forEach(button => button.addEventListener('click', () => answer(Number(button.dataset.answer), false))); startTimer(item);
}
function startTimer(item) { clearInterval(state.timerId); state.timeLeft = state.resumeTime ?? (item.answers.length === 2 ? 30 : 60); state.resumeTime = null; updateTimer(); state.timerId = setInterval(() => { state.timeLeft--; updateTimer(); if (state.timeLeft <= 0) answer(null, true); }, 1000); }
function updateTimer() { const timer = $('timer'); timer.textContent = `${state.timeLeft}s`; timer.classList.toggle('urgent', state.timeLeft <= 5); saveGame(); }
function answer(selected, timedOut) {
  if (state.locked) return; state.locked = true; clearInterval(state.timerId); const item = state.deck[state.question]; const team = state.teams[state.turn]; const buttons = [...document.querySelectorAll('.answer')]; const correct = selected === item.correct; buttons[item.correct].classList.add('correct');
  if (correct) { const earned = 50 + state.timeLeft * 5; team.score += earned; $('feedback').textContent = `¡DECISIÓN ACERTADA! +${earned} PUNTOS`; $('questionCard').classList.add('pop'); } else { team.lives--; if (selected !== null) buttons[selected].classList.add('incorrect'); $('feedback').textContent = timedOut ? '¡TIEMPO AGOTADO! · -1 VIDA' : 'RESPUESTA INCORRECTA · -1 VIDA'; $('feedback').classList.add('error'); $('questionCard').classList.add('shake'); }
  buttons.forEach(button => { button.disabled = true; }); renderScores(); $('correctAnswer').textContent = `${item.answers.length === 2 ? item.correct + 1 : String.fromCharCode(65 + item.correct)}. ${item.answers[item.correct]}`; $('explanationText').textContent = item.explanation; $('wrongExplanation').textContent = getWrongExplanation(item, selected); $('wrongReview').hidden = correct || timedOut; $('explanation').hidden = false; $('continueButton').textContent = team.lives === 0 || state.question === state.deck.length - 1 ? 'VER RESULTADOS' : `TURNO DE ${state.teams[state.turn === 0 ? 1 : 0].name}`; $('questionCard').classList.remove('pop', 'shake'); state.review = { selected, timedOut, correct, feedback: $('feedback').textContent }; saveGame();
}
function restoreReview() { const review = state.review; if (!review) return; clearInterval(state.timerId); const item = state.deck[state.question]; const buttons = [...document.querySelectorAll('.answer')]; buttons[item.correct].classList.add('correct'); if (review.selected !== null && !review.correct) buttons[review.selected].classList.add('incorrect'); buttons.forEach(button => { button.disabled = true; }); $('feedback').textContent = review.feedback; $('feedback').className = review.correct ? 'feedback' : 'feedback error'; $('correctAnswer').textContent = `${item.answers.length === 2 ? item.correct + 1 : String.fromCharCode(65 + item.correct)}. ${item.answers[item.correct]}`; $('explanationText').textContent = item.explanation; $('wrongExplanation').textContent = getWrongExplanation(item, review.selected); $('wrongReview').hidden = review.correct || review.timedOut; $('explanation').hidden = false; $('continueButton').textContent = state.teams[state.turn].lives === 0 || state.question === state.deck.length - 1 ? 'VER RESULTADOS' : `TURNO DE ${state.teams[state.turn === 0 ? 1 : 0].name}`; state.locked = true; }
function getWrongExplanation(item, selected) {
  if (selected === null) return 'No se eligió ninguna opción dentro del tiempo disponible. En este reto también es importante tomar una decisión y comunicar el bloqueo antes de que sea demasiado tarde.';
  if (item.wrongExplanations) return item.wrongExplanations[selected];
  return `Esta afirmación no coincide con el análisis del caso. ${item.explanation}`;
}
function continueTurn() { clearInterval(state.timerId); state.review = null; const teamLost = state.teams.some(team => team.lives === 0); if (teamLost || state.question === state.deck.length - 1) finishGame(); else { state.question++; state.turn = state.turn === 0 ? 1 : 0; saveGame(); renderQuestion(); } }
function finishGame() { showScreen('result'); const [a, b] = state.teams; const eliminated = a.lives === 0 ? a : b.lives === 0 ? b : null; const winner = eliminated ? (eliminated === a ? b : a) : a.score === b.score ? null : (a.score > b.score ? a : b); const tied = !eliminated && !winner; $('resultTitle').textContent = tied ? '¡EMPATE EN PUNTOS!' : `${winner.name} GANA LA MISIÓN`; $('resultSubtitle').textContent = eliminated ? `${eliminated.name} perdió todas sus vidas. En esta misión, quedarse sin corazones significa perder.` : tied ? 'Ambos equipos terminaron con el mismo puntaje.' : 'Se respondieron todas las preguntas. Como ambos conservaron vidas, el puntaje decidió al ganador.'; $('finalScores').innerHTML = state.teams.map(team => `<div class="final-score ${team.color}-final ${team === winner ? 'winner' : ''}"><div class="tag">${team.color === 'blue' ? 'EQUIPO 01' : 'EQUIPO 02'}</div><h3>${team.name}</h3><div class="total">${team.score} <small>PTS</small></div><div class="detail"><span>♥ ${team.lives} vidas</span><span>✦ ${Math.round(team.score / 100)} aciertos</span></div>${team === winner ? '<div class="winner-label">★ EQUIPO GANADOR</div>' : ''}</div>`).join(''); saveGame(); }
function resetGame(useInputNames = true) { localStorage.removeItem(STORAGE_KEY); const names = useInputNames ? [$('blueName').value.trim() || 'Equipo Azul', $('purpleName').value.trim() || 'Equipo Morado'] : state.teams.map(team => team.name); state.teams = [{ name: names[0], score: 0, lives: 3, color: 'blue' }, { name: names[1], score: 0, lives: 3, color: 'purple' }]; state.deck = balancedDeck(); state.question = 0; state.turn = 0; state.locked = false; state.review = null; state.resumeTime = null; renderScores(); }
function startRoulette(useInputNames = true) { resetGame(useInputNames); $('rouletteDisplay').textContent = '¿?'; $('rouletteStatus').textContent = 'La suerte está echada...'; showScreen('roulette'); const first = Math.random() > 0.5 ? 0 : 1; const names = state.teams.map(team => team.name); let ticks = 0; const timer = setInterval(() => { $('rouletteDisplay').textContent = names[ticks % 2]; ticks++; if (ticks > 9) { clearInterval(timer); state.turn = first; $('rouletteDisplay').textContent = state.teams[first].name; $('rouletteStatus').textContent = `¡Empieza ${state.teams[first].name}! Preparando la primera ronda...`; setTimeout(() => { renderQuestion(); showScreen('quiz'); }, 1050); } }, 150); }
$('startButton').addEventListener('click', () => showScreen('context')); $('rouletteButton').addEventListener('click', () => startRoulette(true)); $('restartButton').addEventListener('click', () => startRoulette(false)); $('newTeamsButton').addEventListener('click', () => { localStorage.removeItem(STORAGE_KEY); showScreen('intro'); }); $('continueButton').addEventListener('click', continueTurn); $('helpButton').addEventListener('click', () => $('helpModal').hidden = false); $('closeHelp').addEventListener('click', () => $('helpModal').hidden = true); $('helpModal').addEventListener('click', (event) => { if (event.target === $('helpModal')) $('helpModal').hidden = true; });
function restoreGame() { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return; try { const saved = JSON.parse(raw); if (!saved.deck?.length || !['quiz', 'result'].includes(saved.phase)) return; Object.assign(state, saved, { timerId: null, resumeTime: saved.phase === 'quiz' && !saved.review ? saved.timeLeft : null }); $('blueName').value = state.teams[0].name; $('purpleName').value = state.teams[1].name; renderScores(); if (saved.phase === 'result') { finishGame(); return; } showScreen('quiz'); renderQuestion(); if (saved.review) restoreReview(); } catch { localStorage.removeItem(STORAGE_KEY); } }
restoreGame();
